name: web_api_171020459
description: Restaurant Management System Web API
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mysql1: ^0.20.0
  dotenv: ^4.1.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.9.3
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

